import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next Datadog Demo",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="flex flex-col items-center justify-between p-24">
      <h1>Hello World</h1>
    </main>
  );
}
